[package]
name = "find_duplicates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
env_logger = "0.9.3"
log = "0.4.17"
assert_cmd = "2.0.6"

